sonar.projectKey=aceest-fitness-gym-multi
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.11

# You can add additional properties here if needed, for example:
# sonar.language=py
# sonar.python.coverage.reportPaths=coverage.xml